site_name: Automação de Testes - EBS Domínio
site_description: Documentação - Automação de Testes dos Sistemas Internos
site_url: https://kauagrathwohltr.github.io/ebs-dominio_documentacao-automacao-testes-contabil/
theme:
  name: cinder
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Arial'
    code: 'Courier New'
nav:
  - Home: index.md
  - Projeto: project.md
  - Casos de teste: testCases.md
extra:
  base_url: /